### ISSUE TITLE
Integration with `sbt test`

### ISSUE THREAD

**Issue by y-taka-23** [typelead/sbt-eta#11]
Proposal: How is executing `etlas test` (and `etlas install --enable-tests` if necessary) in the `sbt test` phase?

Coming to consider in the most cases of Eta-scala integration, Eta is in charge "pure" parts of application logic, in which automated testing should perform effectively. I guess we're happy if we can test Eta code in `sbt` workflow.

**Comment by rahulmutt** [comment]
Yeah that sounds like a great idea. I think you can override the test task by adding a step before that executes `etlas test`.
