### ISSUE TITLE
Not published for sbt 1.1.x

### ISSUE THREAD

**Issue by puffnfresh** [typelead/sbt-eta#13]
sbt 1.1.x can't retrieve this plugin because it isn't published.

I can see that the artifact specified as a cross build:

https://github.com/typelead/sbt-eta/blob/6753b764340cb8ee160ca38912dca2e23c9ea77f/build.sbt#L9

To publish all cross build artifacts you have to prefix your command with `+` in sbt, e.g. `+publish`.

**Comment by rahulmutt** [comment]
Thanks for pointing this out! This plugin hasn't been touched in a long time and may not work properly with the latest Etlas. We'll have to copy some code over from the Gradle plugin because it supports pretty much everything.

We'll see if we can allocate some time within the next week to do so.

**Comment by rahulmutt** [comment]
Published `0.2.0` with `+publish` so hopefully this should be addressed.
