### ISSUE TITLE
--maven flag unrecognised by Eta master

### ISSUE THREAD

**Issue by puffnfresh** [typelead/sbt-eta#14]
Trying to use this plugin with Eta as of https://github.com/typelead/eta/commit/5546a4ba9f9b71fc2a147ba1bd958fd3ca41740c gives:

```
etlas: unrecognized 'deps' option `--maven'
```

**Comment by rahulmutt** [comment]
Yeah, we need to update the plugin to get it fixed. We haven't updated the plugin after transitioning to new-build as default.

**Comment by jwiegley** [comment]
@rahulmutt How difficult of a change is this?

**Comment by rahulmutt** [comment]
@jwiegley So the main issue here is that the output of `etlas deps` was modified to provide the entire dependency graph, something the Gradle plugin needed to efficiently maintain a local Maven repository of Eta packages. 

The SBT plugin just needs to update the parsing code to take that into account. For reference, here's the parsing code in the Gradle plugin:

https://github.com/typelead/gradle-eta/blob/master/src/main/java/com/typelead/gradle/utils/EtlasCommand.java#L234-L270

**Comment by rahulmutt** [comment]
@jwiegley It looks like @puffnfresh has made a temporary fix with #15. We'll try to see if we can make a more permanent fix within this week.

**Comment by puffnfresh** [comment]
@rahulmutt I got confirmation from @jwiegley that things are at least kinda working with my workaround.

**Comment by jwiegley** [comment]
@rahulmutt Thank you; I'm trying to build some backend transformations for a compiler written in Scala, and the goal is to demonstrate that they can just as easily be written using Eta.
