### ISSUE TITLE
When are you going to support Etlas 1.5?

### ISSUE THREAD

**Issue by fancellu** [typelead/sbt-eta#16]
As above. 

Latest is 1.5

https://eta-lang.org/docs/user-guides/eta-user-guide/installation/etlas

Thanks

**Comment by rahulmutt** [comment]
There have been several breaking changes in Etlas to accommodate various features and we have not yet been able to catch up. We should be able to extract out a good chunk of the Gradle plugin (which is fully-featured) into a common library which should expedite the release of a working version of this plugin. 

Thanks for indicating your interest. I'll post this issue on social media and see how many people care about this.

**Comment by romac** [comment]
Now that CI is passing after merging #18, this can be closed once v0.3.0 is out :)

**Comment by rahulmutt** [comment]
I have just released 0.3.0 that supports recent versions of Etlas. You can follow up with #23 for updates on when the docs for the plugin will be pushed.
